version: 2
updates:
  - pacakge-ecosystem: "pip"
  directory: "/authn-service"
    schedule:
      interval: "daily"
    labels:
      - "triage-required"
    assignees:
      - "colindembovsky"
    reviewers:
      - "colindembovsky"
    commit-message:
      prefix: "pip"
